base_url = "https://mikerockwood.com"

title = "Mike Rockwood"
description = "Personal portfolio and blog of Mike Rockwood"

default_language = "en"

minify_html = false
compile_sass = true
build_search_index = false

output_dir = "public"

generate_feed = true
feed_filename = "atom.xml"

#ignored_content = ["*.{graphml,xlsx}", "temp.*"]

taxonomies = [
    {name = "categories", feed = true, render = false},
    {name = "tags", feed = true, render = false},
    {name = "tasks", feed = false, render = false},
]

[markdown]
highlight_code = true
highlight_theme = "css"

render_emoji = false
smart_punctuation = true           # `...` to `…`, `"quote"` to `“curly”` etc

external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"

[extra]

menu = [
    {url = "/", name = "Home", slash = true},
    {url = "/work/", name = "Work", slash = true},
	{url = "/about/", name = "About", slash = true},
    {url = "/posts/", name = "Posts", slash = true},
]
menu_footer = [
    {url = "/categories/", name = "Categories", slash = true},
    {url = "/tags/", name = "Tags", slash = true},
    {url = "/sitemap.xml", name = "Sitemap", slash = false},
]

[extra.author]
name = "Mike Rockwood"
email = "rockwood@gmail.com"
avatar = "/images/headshot-cutout.jpg"
bio = "Web developer, designer, and guitar player with a passion for all things digital."

[extra.social]
#feed = true
#mastodon = "@your-user-name"
#twitter = "your-user-name"
#facebook = "your-user-name"
linkedin = "mikerockwood"
github = "mrockwood"
#github_sponsor = "your-user-name"
#stack = "your-user-name"
#twitch = "your-user-name"
#youtube = "channel/your-channel-id"
