backend:
  name: github
  repo: mrockwood/mikerockwood.com
  branch: main

media_folder: "/static/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "content/posts/articles/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - {label: "Tags", name: "tags", widget: "list"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Featured Image", name: "featuredImg", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "bookmarks"
    label: "Bookmarks"
    label_singular: "Bookmark"
    folder: "content/posts/bookmarks/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}      
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - {label: "Tags", name: "tags", widget: "list"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Link", name: "bookmarkOf", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "favorites"
    label: "Favorites"
    label_singular: "Favorite"
    folder: "content/posts/favorites/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Link", name: "likeOf", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "jams"
    label: "Jams"
    label_singular: "Jam"
    folder: "content/posts/jams/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Service", name: "service", widget: "select", options: ['bandcamp','soundcloud','youtube']}
          - {label: "ID", name: "id", widget: "string"}
          - {label: "Thumbnail", name: "thumbnail", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "notes"
    label: "Notes"
    label_singular: "Note"
    folder: "content/posts/notes/"
    create: true
    identifier_field: "body"
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text" }
      - {label: "Path", name: "path", widget: "string" }
      - {label: "Template", name: "template", widget: "string" }
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "replies"
    label: "Replies"
    label_singular: "Reply"
    folder: "content/posts/replies/"
    create: true
    identifier_field: "body"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Reply to URL", name: "inReplyTo", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "reposts"
    label: "Reposts"
    label_singular: "Repost"
    folder: "content/posts/reposts/"
    create: true
    filter: {field: "type", value: "repost"}
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Link", name: "repostOf", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "rsvps"
    label: "RSVPs"
    label_singular: "RSVP"
    folder: "content/posts/rsvps/"
    create: true
    identifier_field: "body"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Event URL", name: "inReplyTo", widget: "string"}
          - {label: "RSVP", name: "rsvp", widget: "select", options: ['yes','no','interested']}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "work"
    label: "Work"
    label_singular: "Work Project"
    folder: "content/work/"
    create: true
    slug: "{{title}}"
    media_folder: ''
    public_folder: ''
    fields:
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - {label: "Tasks", name: "tasks", widget: "list"}
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - {label: "Featured", name: "featured", widget: "boolean", default: false}
          - {label: "Featured Image", name: "featuredImg", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
