name: Fetch Webmentions

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow if needed

permissions:
  contents: write

concurrency:
  group: site-publish
  cancel-in-progress: false

jobs:
  fetch_webmentions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Fetch Webmentions
        env:
          WEBMENTION_TOKEN: ${{ secrets.WEBMENTION_TOKEN }}
        run: |
          mkdir -p static/webmention
          # Fetch webmentions and save (overwrite) to a single file
          curl -s "https://webmention.io/api/mentions.json?token=${WEBMENTION_TOKEN}" -o static/webmention/webmentions.json

      - name: Commit and Push Webmentions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add static/webmention/webmentions.json
          git commit -m "Update webmentions" || echo "No changes to commit"
          # Pull latest changes from main with rebase to avoid conflicts
          git pull --rebase origin main
          # Now push the updated branch
          git push
